apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yh8gveqzu-python
  janus-idp.io/tekton: yh8gveqzu-python
  backstage.io/kubernetes-id: yh8gveqzu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yh8gveqzu-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
