apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yh8gveqzu-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yh8gveqzu-python 
  name: yh8gveqzu-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yh8gveqzu-python 
